### PR TITLE
feat:💪 render mermaid in md #183

### PR DESCRIPTION
**Pull request by ren-yamanashi**
## Changes
- "mermaid" can now be rendered.
   - Installing [vitepress-plugin-mermaid](https://github.com/emersonbottero/vitepress-plugin-mermaid)

## How to check operation

1. Modify package.json
```diff
- "book:build": "vitepress build book/online-book --base /chibivue/"
+ "book:build": "vitepress build book/online-book"
````

2. You can run the following command to check if it is rendering correctly.

```sh
# ~/chibivue
pnpm run book:build
pnpm run book:preview
````

This is a video of the actual build ⬇️

https://github.com/Ubugeeei/chibivue/assets/96362223/805a9eda-0d6c-44d0-846c-335e13bb40f8

## remarks

There is a library that uses `commonJs` as part of the dependencies (dayjs) of [vitepress-plugin-mermaid](https://github.com/emersonbottero/vitepress-plugin-mermaid)

### CODE REVIEW

**Comment by Ubugeeei** [comment]
@ren-yamanashi 
Awesome!!! Thank you!!

**Comment by ren-yamanashi** [comment]
@Ubugeeei 

If you update pnpm-lock.yaml, a conflict will occur...

Even if you install vitepress-plugin-mermaid after updating pnpm-lock.yaml in the main branch, a conflict will occur. 😢 

Is there a good solution?

**Comment by Ubugeeei** [comment]
> If you update pnpm-lock.yaml, a conflict will occur...
> Even if you install vitepress-plugin-mermaid after updating pnpm-lock.yaml in the main branch, a conflict will occur. 😢
> Is there a good solution?

Your fork's main branch has some diffs of chibivue/main.

So, it might be resolved by syncing your fork branch. 😄 

スクリーンショット 2023-12-29 23 49 51

**Comment by Ubugeeei** [comment]
@ren-yamanashi 
Can this PR be merged?
Do you have any other plans to do something?

**Comment by ren-yamanashi** [comment]
@Ubugeeei 

> Can this PR be merged?
Do you have any other plans to do something?

Nothing else!
It took a while to record the video

Please leave a review 🙇

**Comment by Ubugeeei** [comment]
thanks, perfect

**Pull request merged**
