### PR TITLE
docs: correct some mistakes in the document

### PR DESCRIPTION
**Pull request by sor4chi**
Hi, @Ubugeeei, Thank you for this wonderful project!

It's so trivial but I fixed the incorrect document expressions.

### CODE REVIEW

**Comment by Ubugeeei** [comment]
@sor4chi 

Thank you for your contribution!

However, it appears there are some unnecessary changes (such as trailing spaces). 
Would it be possible for you to remove them? 😄

The tail spacing of sentences may affect the way the content is displayed.

**Review by Ubugeeei — CHANGES_REQUESTED** [review]
@sor4chi

Thank you for your contribution!

However, it appears there are some unnecessary changes (such as trailing spaces).
Would it be possible for you to remove them? 😄

The tail spacing of sentences may affect the way the content is displayed.

**Comment by sor4chi** [comment]
@Ubugeeei 
Oh, sorry, I didn't realize that.
By the way, it seems that the fmt command is not being used correctly (even in main, when I type fmt, I get some changes), is it just my environment etc.?

**Comment by Ubugeeei** [comment]
@sor4chi 

> By the way, it seems that the fmt command is not being used correctly (even in main, when I type fmt, I get some 
changes), is it just my environment etc.?

Oh, I can't observe that in my environment.
By the way, when you run the fmt command, are the differences you're seeing in the markdown files?

---

For now, since there are no issues with this PR, I'll go ahead and merge it! Thank you ;D

**Review by Ubugeeei — APPROVED** [review]

**Pull request merged**
